ersion: '3'
  services:
    node:
      build:
        context: .
        dockerfile: Dockerfile
      image: seal1201/todo
      ports:
      - "3000:3000"
    mysql:
      image: mysql
      environment:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DB: db
          MYSQL_ROOT_PASSWORD: password
      ports:
      - 3306:3306
